### PR TITLE
Fixed node ids

### PR DESCRIPTION
**Pull request by michal-h21**
This should fix the issue #6 

LuaTeX changed node id numbering in versio 1.0, it is necessary to use 'node.id` function instead of direct numbers.

### CODE REVIEW

**Comment by raphink** [comment]
Great, thank you!

Is that a breaking change, or will it still work with older versions of LuaTeX?

**Comment by michal-h21** [comment]
@raphink it will work even with older versions, `node.id` was always recommended way

**Comment by raphink** [comment]
ok, thanks @michal-h21

**Comment by LSinev** [comment]
Seems like it is not fully working solution. I think that added lines should be added after each `\begin{luacode}` for draft coloring to work with each package option selected.

**Comment by michal-h21** [comment]
@LSinev you are right, I've created pull request with declarations of variables in all `luacode` environments.

**Pull request merged**
