### PR TITLE
Declare node ids in all luacode environments

### PR DESCRIPTION
**Pull request by michal-h21**
It is necessary to declare the `glyph_id` and `glue_id` variables in all `luacode` environments, in order to be available for checks in the given environments.

### CODE REVIEW

**Comment by raphink** [comment]
@LSinev @michal-h21 so which one should be merged then?

**Comment by michal-h21** [comment]
@raphink I've forgot to merge @LSinev's changes, it should be OK now.

**Comment by LSinev** [comment]
@raphink Please update impnattypo package at CTAN (https://www.ctan.org/pkg/impnattypo).

**Comment by LSinev** [comment]
@raphink Can you please upload updated impnattypo package to CTAN?

**Pull request merged**
